airbnb_dw:
  outputs:
    dev:
      type: postgres
      host: 34.61.160.234
      user: postgres
      password: qkcH@n9qH[%Z=@rY
      port: 5432
      dbname: postgres
      schema: bronze
  target: dev
